add support for upgrading to rawhide

diff --git a/fedora-upgrade b/fedora-upgrade
--- a/fedora-upgrade
+++ b/fedora-upgrade
@@ -7,20 +7,51 @@ function pause() {
    read -p "Hit Enter to continue or Ctrl + C to cancel."
 }
 
-echo "Going to upgrade your Fedora to version 18."
-echo "You may want to read Release Notes:"
-echo "  http://docs.fedoraproject.org/release-notes/"
-pause
-
-if [ 0$FEDORA_VERSION -eq 17 ]; then
+function install_deps() {
   # TODO add -q to all yum and create some kind of progress metter
   # but now be verbose
   rpm -q rpmconf >/dev/null || yum install -y rpmconf
   rpm -q yum-utils >/dev/null || yum install -y yum-utils
+}
 
+function rpmconf_before_upgrade() {
   echo "Going to resolve old .rpmsave and .rpmnew files before upgrading."
   pause 
   rpmconf -a
+}
+
+function install_base() {
+  echo "Going to install missing packages from group 'Minimal Install'"
+  pause
+  yum groupupdate 'Minimal Install'
+}
+
+function rpmconf_after_upgrade() {
+  echo "Going to resolve .rpmsave and .rpmnew files after upgrade."
+  pause
+  rpmconf -a
+  rpmconf --clean
+}
+
+function reset_service_priorities() {
+  echo "Going to reset priorities of services."
+  pause
+  ( cd /etc/rc.d/init.d;
+    for f in *; do
+      [ -x $f ] && /sbin/chkconfig $f resetpriorities || :
+    done # TODO - the same for systemd unit files
+  )
+}
+
+if [ 0$FEDORA_VERSION -eq 17 ]; then
+  echo "Going to upgrade your Fedora to version 18."
+  echo "You may want to read Release Notes:"
+  echo "  http://docs.fedoraproject.org/release-notes/"
+  pause
+
+  install_deps
+  rpmconf_before_upgrade
+
   if [ -f /etc/sysconfig/desktop ]; then
     . /etc/sysconfig/desktop
     if [ "$DISPLAYMANAGER" = GNOME ]; then
@@ -54,24 +85,12 @@ if [ 0$FEDORA_VERSION -eq 17 ]; then
   fi
   rpm --rebuilddb
 
-  echo "Going to install missing packages from group 'Minimal Install'"
-  pause
-  yum groupupdate 'Minimal Install'
+  install_base
   # TODO call package-cleanup --orphans or yum list extras and ask to remove it
   # but the list has a lot of false negatives
 
-  echo "Going to resolve .rpmsave and .rpmnew files after upgrade."
-  pause
-  rpmconf -a
-  rpmconf --clean
-
-  echo "Going to reset priorities of services."
-  pause
-  ( cd /etc/rc.d/init.d; 
-    for f in *; do
-      [ -x $f ] && /sbin/chkconfig $f resetpriorities || :
-    done # TODO - the same for systemd unit files
-  )
+  rpmconf_after_upgrade
+  reset_service_priorities
 
   # https://fedoraproject.org/wiki/Features/DisplayManagerRework
   if [ -n "$preferred" ]; then
@@ -84,6 +103,26 @@ if [ 0$FEDORA_VERSION -eq 17 ]; then
   fi
 
   echo You sucessfullly upgraded to Fedora 18.
+  echo Reboot is strongly suggested.
+elif [ 0$FEDORA_VERSION -eq 18 ]; then
+  echo "Going to upgrade your Fedora to rawhide."
+  echo "Fedora 19 is currently under development."
+  echo "Are you sure?"
+  pause
+
+  install_deps
+  rpmconf_before_upgrade
+
+  yum update -q yum
+  yum clean -q dbcache rpmdb plugins metadata
+  yum --releasever=rawhide --disableplugin=presto distro-sync --nogpgcheck
+
+  install_base
+
+  rpmconf_after_upgrade
+  reset_service_priorities
+
+  echo You sucessfullly upgraded to Fedora 19.
   echo Reboot is strongly suggested.
 else
   echo Upgrading from version $FEDORA_VERSION is not supported.
